# A Heat environment file which can be used to enable a
# a Cinder NetApp backend, configured via puppet
resource_registry:
#  OS::TripleO::ControllerExtraConfigPre: /home/stack/templates/puppet/extraconfig/pre_deploy/controller/cinder-netapp.yaml
  OS::TripleO::Services::CinderBackendNetApp:  /home/stack/templates/puppet/services/cinder-backend-netapp.yaml

parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnableNetappBackend: true
  CinderNetappBackendName: 'tripleo_netapp'
  CinderNetappLogin: 'Dog'
  CinderNetappPassword: 'Beagle'
  CinderNetappServerHostname: 'netapp-nfs'
  CinderNetappServerPort: '80'
  CinderNetappSizeMultiplier: '1.2'
  CinderNetappStorageFamily: 'ontap_cluster'
  CinderNetappStorageProtocol: 'nfs'
  CinderNetappTransportType: 'http'
  CinderNetappVfiler: ''
  CinderNetappVolumeList: ''
  CinderNetappVserver: ''
  CinderNetappPartnerBackendName: ''
  CinderNetappNfsShares: '192.168.23.1:/var/nfs'
  CinderNetappNfsSharesConfig: '/etc/cinder/shares.conf'
  CinderNetappNfsMountOptions: ''
  CinderNetappCopyOffloadToolPath: ''
  CinderNetappControllerIps: ''
  CinderNetappSaPassword: ''
  CinderNetappStoragePools: ''
  CinderNetappHostType: ''
  CinderNetappWebservicePath: '/devmgr/v2'
